demos/ASP.NET Tag Helpers/Controllers/TagHelpersController.cs
using System.Linq;
using jQWidgets.AspNet.Core.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System;
using jQWidgets.AspNetCore.Mvc.TagHelpers;
using System.IO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http.Internal;

namespace jQWidgets.AspNet.Core.Controllers
{
    public class JSONData
    {
        public List<SalesEmployee> Employees
        {
            get;
            set;
        }
        public int TotalRecords
        {
            get;
            set;
        }
    }
    public class TagHelpersController : Controller
    {
        private jQWidgetsDemosContext _context;
        public TagHelpersController(jQWidgetsDemosContext context)
        {
            _context = context;
        }
        //
        // GET: /Widgets/
        public ActionResult Index()
        {
            return View("ScrollView/ScrollView");

            return View("ScrollView/ScrollView", _context.SalesEmployees);
        //    return View("DataTable/DataTableRowDetails", _context.Employee.ToList());
        }
        [HttpPost]
        public FileContentResult ExportData(FormPostBack data)
        { 
             return ExportHelper.ExportData(data);
        }

        [HttpPost]
        public string GetEmployees()
        {
            List<SalesEmployee> allEmployees = _context.SalesEmployees.ToList(); 
            JSONData data = new JSONData();
            data.TotalRecords = allEmployees.Count;
            data.Employees = allEmployees;
            return JsonConvert.SerializeObject(data);
        }

        [HttpPost]
        public string GetChildren(string jsonData)
        {
            JToken token = JObject.Parse(jsonData);
            string id = (string)token.SelectToken("ID");
            List<SalesEmployee> allEmployees = _context.SalesEmployees.ToList();
            JSONData data = new JSONData();
            List<SalesEmployee> employees = new List<SalesEmployee>();
            for (int i = 0; i < allEmployees.Count; i++)
            {
                if (String.IsNullOrEmpty(id))
                {
                    if (i < 5)
                    {
                        employees.Add(allEmployees[i]);
                    }
                }
                else
                {
                    if (allEmployees[i].ReportsTo == Int32.Parse(id))
                    {
                        employees.Add(allEmployees[i]);
                    }
                }
            }
            data.TotalRecords = allEmployees.Count;
            data.Employees = employees;
            return JsonConvert.SerializeObject(data);
        }

        [HttpPost]
        public string GetPageData(string jsonData)
        {
            JToken token = JObject.Parse(jsonData);

            List<JToken> filterGroups = token.SelectToken("filterGroups").Children().ToList();
            int pageSize = (int)token.SelectToken("pagesize");
            int pageNum = (int)token.SelectToken("pagenum");
            string sortField = (string)token.SelectToken("sortdataField");
            string sortOrder = (string)token.SelectToken("sortorder");
            int count = 0;
            List<SalesEmployee> employees = new List<SalesEmployee>();
            List<SalesEmployee> allEmployees = _context.SalesEmployees.ToList();
            if (sortField != "")
            {
                if (sortOrder == "asc")
                {              
                    allEmployees = (from p in allEmployees
                                    orderby (p.GetType().GetProperty(sortField).GetValue(p))
                                 select p).ToList();

                }
                else if (sortOrder == "desc")
                {
                    allEmployees = (from p in allEmployees
                                    orderby (p.GetType().GetProperty(sortField).GetValue(p)) descending
                                    select p).ToList();
                }
            }
            if (filterGroups.Count > 0)
            {
                List<SalesEmployee> filteredEmployees = allEmployees;
                for (int j = 0; j < filterGroups.Count; j++)
                {
                    List<JToken> filters = filterGroups[j].SelectToken("filters").Children().ToList();

                    List<SalesEmployee> filterGroup = filteredEmployees;
                    List<SalesEmployee> filterGroupResult = new List<SalesEmployee>();
                    for (int i = 0; i < filters.Count; i++)
                    {
                        string filterLabel = (string)filters[i].SelectToken("label");
                        string filterValue = (string)filters[i].SelectToken("value");
                        string filterDataField = (string)filters[i].SelectToken("field");
                        string filterCondition = (string)filters[i].SelectToken("condition");
                        string filterType = (string)filters[i].SelectToken("type");
                        string filterOperator = (string)filters[i].SelectToken("operator");

                        List<SalesEmployee> currentResult = new List<SalesEmployee>();

                        switch (filterCondition)
                        {
                            case "NOT_EMPTY":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)) != null)
                                                     select p).ToList();
                                break;
                            case "NOT_NULL":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString() != "")
                                                     select p).ToList();
                                break;
                            case "NULL":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)) == null)
                                                     select p).ToList();
                                break;
                            case "EMPTY":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString() == "")
                                                     select p).ToList();
                                break;
                            case "CONTAINS_CASE_SENSITIVE":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString().Contains(filterValue))
                                                     select p).ToList();
                                break;
                            case "CONTAINS":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString().IndexOf(filterValue, StringComparison.CurrentCultureIgnoreCase) != -1)
                                                     select p).ToList();
                                break;
                            case "DOES_NOT_CONTAIN_CASE_SENSITIVE":
                                currentResult = (from p in filterGroup
                                                 where (!(p.GetType().GetProperty(filterDataField).GetValue(p)).ToString().Contains(filterValue))
                                                     select p).ToList();
                                break;
                            case "DOES_NOT_CONTAIN":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString().IndexOf(filterValue, StringComparison.CurrentCultureIgnoreCase) == -1)
                                                     select p).ToList();
                                break;
                            case "EQUAL_CASE_SENSITIVE":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString() == filterValue)
                                                     select p).ToList();
                                break;
                            case "EQUAL":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString().IndexOf(filterValue, StringComparison.CurrentCultureIgnoreCase) == 0)
                                                     select p).ToList();
                                break;
                            case "NOT_EQUAL_CASE_SENSITIVE":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString() != filterValue)
                                                     select p).ToList();
                                break;
                            case "NOT_EQUAL":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString().IndexOf(filterValue, StringComparison.CurrentCultureIgnoreCase) != 0)
                                                     select p).ToList();
                                break;
                            case "GREATER_THAN":
                                currentResult = (from p in filterGroup

demos/ASP.NET Tag Helpers/Views/TagHelpers/TreeGrid/TreeGrid.cshtml
<script src="~/jqwidgets/jqxbuttons.js"></script>
<script src="~/jqwidgets/jqxscrollbar.js"></script>
<script src="~/jqwidgets/jqxlistbox.js"></script>
<script src="~/jqwidgets/jqxdropdownlist.js"></script>
<script src="~/jqwidgets/jqxdatatable.js"></script>
<script src="~/jqwidgets/jqxtreegrid.js"></script>
@model IEnumerable<jQWidgets.AspNet.Core.Models.Employee>

@{
    ViewData["Title"] = "ASP .NET MVC TreeGrid Example";
}
@{
    var employee = Model.FirstOrDefault();
}
<script>
    var treeGridInstance;
    function getInstance(instance)
    {
        treeGridInstance = instance;
    }
    function treeGridReady()
    {
        treeGridInstance.expandRow(2);
    }
</script>
<jqx-tree-grid key-datafield-for="@(employee.EmployeeID)" ready="treeGridReady()" source-id-for="@(employee.EmployeeID)" instance="getInstance()" parent-datafield-for="@(employee.ManagerID)" theme="@ViewData["Theme"]" sortable="true" width="850" source="Model"> 
    <jqx-tree-grid-columns>
        <jqx-tree-grid-column dataField-for="@(employee.FirstName)" width="100" text="First Name"></jqx-tree-grid-column>
        <jqx-tree-grid-column datafield-for="@(employee.LastName)" width="100" text="Last Name"></jqx-tree-grid-column>
        <jqx-tree-grid-column datafield-for="@(employee.Title)" width="150"></jqx-tree-grid-column>
        <jqx-tree-grid-column datafield-for="@(employee.Address)" width="200"></jqx-tree-grid-column>
        <jqx-tree-grid-column datafield-for="@(employee.City)" width="150"></jqx-tree-grid-column>
        <jqx-tree-grid-column datafield-for="@(employee.Country)"></jqx-tree-grid-column>
    </jqx-tree-grid-columns>
</jqx-tree-grid>

demos/ASP.NET Tag Helpers/Views/TagHelpers/TreeGrid/TreeGridConditionalFormatting.cshtml
<script src="~/jqwidgets/jqxbuttons.js"></script>
<script src="~/jqwidgets/jqxscrollbar.js"></script>
<script src="~/jqwidgets/jqxlistbox.js"></script>
<script src="~/jqwidgets/jqxdropdownlist.js"></script>
<script src="~/jqwidgets/jqxdatatable.js"></script>
<script src="~/jqwidgets/jqxtreegrid.js"></script>

@model IEnumerable<jQWidgets.AspNet.Core.Models.SalesEmployee>

@{
    ViewData["Title"] = "ASP .NET MVC TreeGrid Conditional Formatting Example";
}
@{
    var employee = Model.FirstOrDefault();
}
<style>
    .max {
        color: black\9;
        background-color: #63be7b\9;
    }

    .avg {
        color: black\9;
        background-color: #f8e984\9;
    }

    .minavg {
        color: black\9;
        background-color: #f9806f\9;
    }

    .min {
        color: black\9;
        background-color: #f8696b\9;
    }

    .max:not(.jqx-grid-cell-hover):not(.jqx-grid-cell-selected), .jqx-widget .max:not(.jqx-grid-cell-hover):not(.jqx-grid-cell-selected) {
        color: black;
        background-color: #63be7b;
    }

    .avg:not(.jqx-grid-cell-hover):not(.jqx-grid-cell-selected), .jqx-widget .avg:not(.jqx-grid-cell-hover):not(.jqx-grid-cell-selected) {
        color: black;
        background-color: #f8e984;
    }

    .minavg:not(.jqx-grid-cell-hover):not(.jqx-grid-cell-selected), .jqx-widget .minavg:not(.jqx-grid-cell-hover):not(.jqx-grid-cell-selected) {
        color: black;
        background-color: #f9806f;
    }

    .min:not(.jqx-grid-cell-hover):not(.jqx-grid-cell-selected), .jqx-widget .min:not(.jqx-grid-cell-hover):not(.jqx-grid-cell-selected) {
        color: black;
        background-color: #f8696b;
    }
</style>

<script>
    var treeGridInstance;
    function getInstance(instance)
    {
        treeGridInstance = instance;
    }
    function treeGridReady()
    {
        treeGridInstance.expandRow(2);
    }
    function cellClass (row, dataField, cellText, rowData) {
        var cellValue = rowData[dataField];
        if (cellValue < 2) {
            return "min";
        }
        if (cellValue < 4) {
            return "minavg";
        }
        if (cellValue < 6) {
            return "avg";
        }
        return "max";
    }
</script>
<jqx-tree-grid key-datafield-for="@(employee.ID)" pageable="true" ready="treeGridReady()" sourceId-for="@(employee.ID)" instance="getInstance()" parent-datafield-for="@(employee.ReportsTo)" theme="@ViewData["Theme"]" sortable="true" width="850" source="Model"> 
    <jqx-tree-grid-columns>
        <jqx-tree-grid-column dataField-for="@(employee.FirstName)" width="100" text="First Name"></jqx-tree-grid-column>
        <jqx-tree-grid-column dataField-for="@(employee.LastName)" width="100" text="Last Name"></jqx-tree-grid-column>
        <jqx-tree-grid-column dataField-for="@(employee.ProductName)" width="150"></jqx-tree-grid-column>
        <jqx-tree-grid-column dataField-for="@(employee.Quantity)" width="200"></jqx-tree-grid-column>
        <jqx-tree-grid-column cell-class-name="cellClass()" dataField-for="@(employee.Price)"></jqx-tree-grid-column>
    </jqx-tree-grid-columns>
</jqx-tree-grid>

demos/ASP.NET Tag Helpers/Views/TagHelpers/TreeGrid/TreeGridLoadOnDemand.cshtml
<script src="~/jqwidgets/jqxbuttons.js"></script>
<script src="~/jqwidgets/jqxscrollbar.js"></script>
<script src="~/jqwidgets/jqxlistbox.js"></script>
<script src="~/jqwidgets/jqxdropdownlist.js"></script>
<script src="~/jqwidgets/jqxdatatable.js"></script>
<script src="~/jqwidgets/jqxtreegrid.js"></script>

@model IEnumerable<jQWidgets.AspNet.Core.Models.SalesEmployee>

@{
    ViewData["Title"] = "ASP .NET MVC TreeGrid Example";
}
@{
    var employee = Model.FirstOrDefault();
}
<script>
    function virtualModeCreateRecords(expandedRecord, done)
    {
        var json = expandedRecord ? JSON.stringify(expandedRecord) : "{ReportsTo: null}";
        var source =
            {
                type: 'POST', dataType: 'json',
                dataFields:
                    [
                        { name: "FirstName", type: "string" },
                        { name: "LastName", type: "string" },
                        { name: "ProductName", type: "string" },
                        { name: "ID", type: "string" },
                        { name: "ReportsTo", type: "string" }
                    ],
                data: { 'jsonData': json },
                root: "Employees",
                id: "ID",
                url: "@Url.Action("GetChildren","TagHelpers")"
                };

        var dataAdapter = new $.jqx.dataAdapter(source,
        {
            loadComplete: function () {
                done(dataAdapter.records);
            },
            loadError: function (xhr, status, error) {
                done(false);
            }
        });
        dataAdapter.dataBind();
    }
    function virtualModeRecordCreating(record)
    {
        if (record.level == 1) {
            // by setting the record's leaf member to true, you will define the record as a leaf node.
            record.leaf = true;
        }
    }
</script>
<jqx-tree-grid pageable="true" virtual-mode-create-records="virtualModeCreateRecords()" virtual-mode-record-creating="virtualModeRecordCreating()" theme="@ViewData["Theme"]" width="600"> 
    <jqx-tree-grid-columns>
        <jqx-tree-grid-column dataField-for="@(employee.FirstName)" width="200" text="First Name"></jqx-tree-grid-column>
        <jqx-tree-grid-column dataField-for="@(employee.LastName)" width="200" text="Last Name"></jqx-tree-grid-column>
        <jqx-tree-grid-column dataField-for="@(employee.ProductName)" width="200"></jqx-tree-grid-column>
    </jqx-tree-grid-columns>
</jqx-tree-grid>